apiVersion: v1
kind: Service

metadata:
  name: {{ include "myapp.fullname" . }}-headless

spec:
  clusterIP: None

  selector:
    app: {{ include "myapp.fullname" . }}

  ports:
    - port: 27017
      targetPort: 27017
